version: '3.7'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro,rslave'
# optional
  cadvisor:
    image: google/cadvisor:latest
    restart: unless-stopped
    ports:
      - 9101:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
