version: '3.7'

services:
  prometheus:
    network_mode: host
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana:
    external: false
